export const UPDATE_DATERANGE = "UPDATE_DATERANGE";
export const UPDATE_FREQUENCY = "UPDATE_FREQUENCY";
export const UPDATE_LONG_ONLY = "UPDATE_LONG_ONLY";
export const UPDATE_MARKET = "UPDATE_MARKET";
