export const UPDATE_DATERANGE = "UPDATE_DATERANGE";
export const UPDATE_FREQUENCY = "UPDATE_FREQUENCY";
export const UPDATE_LONG_ONLY = "UPDATE_LONG_ONLY";
export const UPDATE_MARKET = "UPDATE_MARKET";
export const GET_ASSET_RETURN = "GET_ASSET_RETURN";
export const UPDATE_SELECTED_ASSETS = "UPDATE_SELECTED_ASSETS";
export const UPDATE_EXPECTED_RETURN_METHOD = "UPDATE_EXPECTED_RETURN_METHOD";
export const UPDATE_COVARIANCE_METHOD = "UPDATE_COVARIANCE_METHOD";
export const WAITING_OPTIMIZATION_RESULTS = "WAITING_OPTIMIZATION_RESULTS";
export const OPTIMIZATION_ERROR = "OPTIMIZATION_ERROR";
export const RECEIVED_OPTIMIZATION_RESULTS = "RECEIVED_OPTIMIZATION_RESULTS";
export const WAITING_ASSET_RETURN_RESULTS = "WAITING_ASSET_RETURN_RESULTS";
export const ASSET_RETURN_ERROR = "ASSET_RETURN_ERROR";
export const RECEIVED_ASSET_RETURN_RESULTS = "RECEIVED_ASSET_RETURN_RESULTS";
export const UPDATE_PORTFOLIO_SELECTION_METHOD =
  "UPDATE_PORTFOLIO_SELECTION_METHOD";
